apiVersion: apps/v1
kind: Deployment
metadata:
  name: devicemart
  labels:
    app: devicemart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devicemart
  template:
    metadata:
      labels:
        app: devicemart
    spec:
      containers:
        - name: devicemart
          image: anazibinurasheed/devicemart
          ports:
            - containerPort: 3000
          env:
            - name: DB_USER
              valueFrom: 
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-user
            - name: DB_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
            - name: DB_NAME
              valueFrom: 
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-db-name
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: postgres-host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: postgres-port
---
apiVersion: v1
kind: Service
metadata:
  name: devicemart-service
spec:
  selector:
    app: devicemart
  type: LoadBalancer ##external service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001  