// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/anazibinurasheed/project-device-mart/pkg/api"
	"github.com/anazibinurasheed/project-device-mart/pkg/api/handler"
	"github.com/anazibinurasheed/project-device-mart/pkg/config"
	"github.com/anazibinurasheed/project-device-mart/pkg/db"
	"github.com/anazibinurasheed/project-device-mart/pkg/repository"
	"github.com/anazibinurasheed/project-device-mart/pkg/usecase"
)

// Injectors from wire.go:

func InitializeAPI(cfg config.Config) (*api.ServerHTTP, error) {
	gormDB, err := db.ConnectToDatabase(cfg)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(gormDB)
	userUseCase := usecase.NewUserUseCase(userRepository)
	userHandler := handler.NewUserHandler(userUseCase)
	adminRepository := repository.NewAdminRepository(gormDB)
	adminUseCase := usecase.NewAdminUseCase(adminRepository, userRepository)
	adminHandler := handler.NewAdminHandler(adminUseCase)
	productRepository := repository.NewProductRepository(gormDB)
	orderRepository := repository.NewOrderRepository(gormDB)
	productUseCase := usecase.NewProductUseCase(productRepository, orderRepository)
	productHandler := handler.NewProductHandler(productUseCase)
	commonUseCase := usecase.NewCommonUseCase(userRepository, adminRepository)
	commonHandler := handler.NewCommonHandler(commonUseCase)
	cartRepository := repository.NewCartRepository(gormDB)
	couponRepository := repository.NewCouponRepository(gormDB)
	cartUseCase := usecase.NewCartUseCase(cartRepository, couponRepository)
	cartHandler := handler.NewCartHandler(cartUseCase)
	paymentRepository := repository.NewPaymentRepository(gormDB)
	orderUseCase := usecase.NewOrderUseCase(userRepository, cartUseCase, paymentRepository, orderRepository, couponRepository)
	orderHandler := handler.NewOrderHandler(orderUseCase)
	couponUseCase := usecase.NewCouponUseCase(couponRepository)
	couponHandler := handler.NewCouponHandler(couponUseCase)
	refferalRepository := repository.NewRefferalRepository(gormDB)
	refferalUseCase := usecase.NewRefferalUseCase(refferalRepository, orderRepository)
	refferalHandler := handler.NewRefferalHandler(refferalUseCase)
	serverHTTP := api.NewServerHTTP(userHandler, adminHandler, productHandler, commonHandler, cartHandler, orderHandler, couponHandler, refferalHandler)
	return serverHTTP, nil
}
