# workflow 

name: devicemart workflow


on: push
 jobs:
  run_code_checks: 
   runs-on: ubuntu-latest
   steps:
    - name: check out repository code 
      uses: actions/checkout@v2
    - name: setup go 
      uses: actions/setup-go@v2
      with:
       go version:1.16
    - name: run linting
      run : |
        go fmt ./...
        go vet ./...
    - name: run tests
      run: go test ./...